### ISSUE TITLE
[META] MAINTAINERS.md refer to other MAINTAINERS.md 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/.github#121]
### What is the bug?

MAINTAINERS format has undergone several iterations and many repos have an older format that duplicates text in [RESPONSIBILITIES.md](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md).

### What is the expected behavior?

Standardize maintainers to this.

```
## Overview

This document contains a list of maintainers in this repo. See [opensearch-project/.github/RESPONSIBILITIES.md](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#maintainer-responsibilities) that explains what the role of maintainer means, what maintainers do in this and other repos, and how they should be doing it. If you're interested in contributing, and becoming a maintainer, see [CONTRIBUTING](CONTRIBUTING.md).

## Current Maintainers

| Maintainer     | GitHub ID                                     | Affiliation |
| -------------- | --------------------------------------------- | ----------- |

```

- [x] https://github.com/opensearch-project/alerting/pull/734
- [x] https://github.com/opensearch-project/alerting-dashboards-plugin/pull/435
- [x] https://github.com/opensearch-project/anomaly-detection/pull/771
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/388
- [x] https://github.com/opensearch-project/asynchronous-search/pull/218
- [x] https://github.com/opensearch-project/common-utils/pull/343
- [x] https://github.com/opensearch-project/reporting/pull/619
- [x] https://github.com/opensearch-project/dashboards-visualizations/pull/153
- [x] https://github.com/opensearch-project/data-prepper/pull/2117
- [x] https://github.com/opensearch-project/documentation-website/pull/2339
- [x] https://github.com/opensearch-project/index-management/pull/650
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/pull/539
- [x] https://github.com/opensearch-project/job-scheduler/pull/296
- [x] https://github.com/opensearch-project/k-NN/pull/709
- [x] https://github.com/opensearch-project/logstash-output-opensearch/pull/185
- [x] https://github.com/opensearch-project/notifications/pull/589
- [x] https://github.com/opensearch-project/OpenSearch/pull/5717
- [x] https://github.com/opensearch-project/opensearch-build/pull/3046
- [x] https://github.com/opensearch-project/opensearch-cli/pull/68
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3180
- [x] https://github.com/opensearch-project/opensearch-devops/pull/101
- [x] https://github.com/opensearch-project/opensearch-plugins/pull/192
- [x] https://github.com/opensearch-project/performance-analyzer/pull/359
- [x] https://github.com/opensearch-project/performance-analyzer-rca/pull/267
- [x] https://github.com/opensearch-project/perftop/pull/62
- [x] https://github.com/opensearch-project/piped-processing-language/pull/17
- [x] https://github.com/opensearch-project/project-website/pull/1265
- [x] https://github.com/opensearch-project/security/pull/2376
- [x] https://github.com/opensearch-project/security-dashboards-plugin/pull/1288
- [x] https://github.com/opensearch-project/sql/pull/1224
- [x] https://github.com/opensearch-project/opensearch-plugin-template-java/pull/47
- [x] https://github.com/opensearch-project/geospatial/pull/200
- [x] https://github.com/opensearch-project/cross-cluster-replication/pull/673
- [x] https://github.com/opensearch-project/opensearch-go/pull/208
- [x] https://github.com/opensearch-project/opensearch-java/pull/314
- [x] https://github.com/opensearch-project/opensearch-py/pull/261
- [x] https://github.com/opensearch-project/opensearch-js/pull/358
- [x] https://github.com/opensearch-project/helm-charts/pull/367
- [x] https://github.com/opensearch-project/ansible-playbook/pull/107
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/433
- [x] https://github.com/opensearch-project/opensearch-dashboards-test-library/pull/27
- [x] https://github.com/opensearch-project/opensearch-ci/pull/235
- [x] https://github.com/opensearch-project/project-website-search/pull/42
- [x] https://github.com/opensearch-project/opensearch-dsl-py/pull/88
- [x] https://github.com/opensearch-project/opensearch-clients/pull/45
- [x] https://github.com/opensearch-project/opensearch-rs/pull/99
- [x] https://github.com/opensearch-project/opensearch-php/pull/114
- [x] https://github.com/opensearch-project/opensearch-ruby/pull/132
- [x] https://github.com/opensearch-project/ml-commons/pull/659
- [x] https://github.com/opensearch-project/opensearch-benchmark/pull/214
- [x] https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/60
- [x] https://github.com/opensearch-project/observability/pull/1367
- [x] https://github.com/opensearch-project/opensearch-net/pull/132
- [x] https://github.com/opensearch-project/opensearch-oci-object-storage/pull/23
- [x] https://github.com/opensearch-project/dashboards-desktop/pull/33
- [x] https://github.com/opensearch-project/logstash-input-opensearch/pull/39
- [x] https://github.com/opensearch-project/maps/pull/35
- [x] https://github.com/opensearch-project/opensearch-api-specification/pull/72
- [x] https://github.com/opensearch-project/dashboards-anywhere/pull/138
- [x] https://github.com/opensearch-project/security-analytics/pull/240
- [x] https://github.com/opensearch-project/opensearch-catalog/pull/8
- [x] https://github.com/opensearch-project/dashboards-maps/pull/164
- [x] https://github.com/opensearch-project/i18n-plugin/pull/15
- [x] https://github.com/opensearch-project/opensearch-testcontainers/pull/54
- [x] https://github.com/opensearch-project/oui/pull/184
- [x] https://github.com/opensearch-project/opensearch-sdk-java/pull/307
- [x] https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/284
- [x] https://github.com/opensearch-project/dashboards-docker-images/pull/6
- [x] https://github.com/opensearch-project/docker-images/pull/10
- [x] https://github.com/opensearch-project/opensearch-build-libraries/pull/108
- [x] https://github.com/opensearch-project/ux/pull/58
- [x] https://github.com/opensearch-project/opensearch-hadoop/pull/47
- [x] https://github.com/opensearch-project/spring-data-opensearch/pull/84
- [x] https://github.com/opensearch-project/neural-search/pull/95
- [x] https://github.com/opensearch-project/simple-schema/pull/56
- [x] https://github.com/opensearch-project/terraform-provider-opensearch/pull/11
- [x] https://github.com/opensearch-project/project-tools/pull/44
- [x] https://github.com/opensearch-project/dashboards-search-relevance/pull/108
- [x] https://github.com/opensearch-project/opensearch-py-ml/pull/64
- [x] https://github.com/opensearch-project/opensearch-cluster-cdk/pull/5
- [x] https://github.com/opensearch-project/oui-docs-cdk/pull/6
- [x] https://github.com/opensearch-project/search-processor/pull/77
- [x] https://github.com/opensearch-project/dashboards-query-workbench/pull/18
- [x] https://github.com/opensearch-project/sql-cli/pull/7
- [x] https://github.com/opensearch-project/sql-jdbc/pull/47
- [x] https://github.com/opensearch-project/sql-odbc/pull/28
- [x] https://github.com/opensearch-project/dashboards-observability/pull/164

**Comment by dblock** [comment]
Week 1: 41/87 merged.
