### ISSUE TITLE
[Meta] Remove "Beta" label

### ISSUE THREAD

**Issue by dblock** [opensearch-project/.github#64]
**What is the bug?**

There are dozens of issues labeled beta. These are usually inside the but_template.md. 

OpenSearch beta has long sailed.

https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aopensearch-project+label%3ABeta

**What is the expected behavior?**

Beta tag needs to be removed from everywhere.

![](https://user-images.githubusercontent.com/542335/161598974-ef05e29d-d836-463e-ae7b-97ada50ba8d3.png)

- [x] https://github.com/opensearch-project/common-utils/pull/154
- [x] https://github.com/opensearch-project/ml-commons/pull/273
- [x] https://github.com/opensearch-project/alerting-dashboards-plugin/pull/205
- [x] https://github.com/opensearch-project/alerting/pull/382
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/226
- [x] https://github.com/opensearch-project/anomaly-detection/pull/488
- [x] https://github.com/opensearch-project/asynchronous-search/pull/126
- [x] https://github.com/opensearch-project/dashboards-reports/pull/328
- [x] https://github.com/opensearch-project/dashboards-visualizations/pull/59
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/pull/168
- [x] https://github.com/opensearch-project/index-management/pull/324
- [x] https://github.com/opensearch-project/job-scheduler/pull/165
- [x] https://github.com/opensearch-project/k-NN/pull/351
- [x] https://github.com/opensearch-project/notifications/pull/396
- [x] https://github.com/opensearch-project/performance-analyzer/pull/177
- [x] https://github.com/opensearch-project/performance-analyzer-rca/pull/154
- [x] https://github.com/opensearch-project/security-dashboards-plugin/pull/931
- [x] https://github.com/opensearch-project/security/pull/1740
- [x] https://github.com/opensearch-project/sql/pull/531
- [x] https://github.com/opensearch-project/cross-cluster-replication/pull/349
- [x] https://github.com/opensearch-project/observability/pull/662

**Comment by dblock** [comment]
Removed beta label from all projects and from open issues.
